<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>My Blog</title>

  <!-- Boostrap v4 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Pygments code highlighting -->
  <link rel="stylesheet" href=" /css/pygments-vs.css">

  <link rel="stylesheet" href=" /css/uikit.css">
  <link rel="stylesheet" href=" /css/main.css">
</head>
<body>
  
  <div class="container">
    
  <h1><a href="/"><img src="/assets/images/emblem.svg" /></a> async, EventHandler and Exceptions</h1>
  <div class="content">
    <p>Hopefully this will </p>
<ul>
<li>Help lost developers who dealt with a similar situation to myself</li>
<li>Get feedback if this is a good approach to dealing with throwing exceptions in an <code>async</code> <code>EventHandler</code></li>
</ul>
<h2 id="throwing-exceptions-from-events">Throwing Exceptions From Events</h2>
<p>A developer would typically add an event to their class</p>
<div class="highlight"><pre><span></span><span class="k">public</span> <span class="k">class</span> <span class="nc">MyClass</span>
<span class="p">{</span>
    <span class="k">public</span> <span class="k">event</span> <span class="n">EventHandler</span> <span class="n">OnSomeEvent</span><span class="p">;</span>

    <span class="k">public</span> <span class="k">void</span> <span class="nf">TriggerSomeEvent</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="n">OnSomeEvent</span><span class="p">?.</span><span class="n">Invoke</span><span class="p">(</span><span class="k">this</span><span class="p">,</span> <span class="k">new</span> <span class="n">EventArgs</span><span class="p">());</span>
        <span class="p">}</span>
        <span class="k">catch</span><span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// Handle exception things here</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></div>


<p>A subscriber class may listen to the event using </p>
<div class="highlight"><pre><span></span><span class="n">thatClass</span><span class="p">.</span><span class="n">OnSomeEvent</span> <span class="p">+=</span> <span class="p">(</span><span class="n">sender</span><span class="p">,</span> <span class="n">args</span><span class="p">)</span> <span class="p">=&gt;</span> <span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="s">&quot;Some event happened&quot;</span><span class="p">);</span>
</pre></div>


<p>If the subscriber was to throw an exception, or it failed to handle an exception on it's own. It would be passed back to <code>TriggerSomeEvent</code> </p>
<h2 id="throwing-exceptions-from-async-events">Throwing Exceptions From <code>async</code> Events</h2>
<p>This is where things get tricky. When a listener class subscribes with an async delegate, and throws an exception. it does no get handled by <code>TriggerSomeEvent</code></p>
<div class="highlight"><pre><span></span><span class="n">thatClass</span><span class="p">.</span><span class="n">OnSomeEvent</span> <span class="p">+=</span> <span class="k">async</span> <span class="p">(</span><span class="n">sender</span><span class="p">,</span> <span class="n">args</span><span class="p">)</span> <span class="p">=&gt;</span> 
<span class="p">{</span>
    <span class="k">await</span> <span class="n">Task</span><span class="p">.</span><span class="n">Yield</span><span class="p">();</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="p">();</span>
<span class="p">}</span>
</pre></div>


<p><code>TriggerSomeEvent</code> will never catch the event for a couple of reasons. The first being that the above delegate is <code>async void</code>, there's no <code>Task</code> to store the exception into, and that the delegate is not awaited. </p>
<p>After exploring my my options, I considered using an <code>AsyncEventHandler</code></p>
<div class="highlight"><pre><span></span><span class="k">public</span> <span class="k">delegate</span> <span class="n">Task</span> <span class="nf">AsyncEventHandler</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">);</span>
<span class="c1">// and</span>
<span class="k">public</span> <span class="k">delegate</span> <span class="n">Task</span> <span class="n">AsyncEventHandler</span><span class="p">&lt;</span><span class="n">TEventArgs</span><span class="p">&gt;(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">TEventArgs</span> <span class="n">e</span><span class="p">);</span>
</pre></div>


<p>Compared to C#'s EventHander </p>
<div class="highlight"><pre><span></span><span class="k">public</span> <span class="k">delegate</span> <span class="k">void</span> <span class="nf">EventHandler</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">);</span>
<span class="c1">// and</span>
<span class="k">public</span> <span class="k">delegate</span> <span class="k">void</span> <span class="n">EventHandler</span><span class="p">&lt;</span><span class="n">TEventArgs</span><span class="p">&gt;(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">TEventArgs</span> <span class="n">e</span><span class="p">);</span>
</pre></div>


<p>The only difference being that AsyncEventHandler returns type <code>Task</code> instead of <code>void</code></p>
<p>Invoking an <code>AsyncEventHandler</code> is slightly more complicated</p>
<div class="highlight"><pre><span></span><span class="k">public</span> <span class="k">delegate</span> <span class="n">Task</span> <span class="nf">AsyncEventHandler</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">);</span>

<span class="k">public</span> <span class="k">class</span> <span class="nc">MyEventClass</span>
<span class="p">{</span>
    <span class="c1">/// &lt;summary&gt;</span>
    <span class="c1">/// A async event delegate</span>
    <span class="c1">/// &lt;/summary&gt;</span>
    <span class="k">public</span> <span class="n">AsyncEventHandler</span> <span class="n">MyAsyncEvent</span><span class="p">;</span>

    <span class="c1">/// &lt;summary&gt;</span>
    <span class="c1">/// A typical event delegate</span>
    <span class="c1">/// &lt;/summary&gt;</span>
    <span class="k">public</span> <span class="n">EventHandler</span> <span class="n">MyEvent</span><span class="p">;</span>

    <span class="c1">/// &lt;summary&gt;</span>
    <span class="c1">/// Invokes all listeners and awaits any that are async</span>
    <span class="c1">/// &lt;/summary&gt;</span>
    <span class="c1">/// &lt;returns&gt;&lt;/returns&gt;</span>
    <span class="k">public</span> <span class="k">async</span> <span class="n">Task</span> <span class="nf">TriggerAsyncEvent</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="k">await</span> <span class="n">Task</span><span class="p">.</span><span class="n">WhenAll</span><span class="p">(</span><span class="n">GetAwaitableAsyncEvents</span><span class="p">()).</span><span class="n">ConfigureAwait</span><span class="p">(</span><span class="k">false</span><span class="p">);</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// Exceptions are caught here</span>
        <span class="p">}</span>
    <span class="p">}</span>

    <span class="c1">/// &lt;summary&gt;</span>
    <span class="c1">/// Invoked from &lt;see cref=&quot;TriggerAsyncEvent&quot;/&gt; to return async delegates to await</span>
    <span class="c1">/// &lt;/summary&gt;</span>
    <span class="c1">/// &lt;returns&gt;&lt;/returns&gt;</span>
    <span class="k">private</span> <span class="n">IEnumerable</span><span class="p">&lt;</span><span class="n">Task</span><span class="p">&gt;</span> <span class="n">GetAwaitableAsyncEvents</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">foreach</span> <span class="p">(</span><span class="kt">var</span> <span class="n">listener</span> <span class="k">in</span> <span class="n">MyAsyncEvent</span><span class="p">.</span><span class="n">GetInvocationList</span><span class="p">())</span>
            <span class="k">if</span> <span class="p">(</span><span class="n">listener</span><span class="p">.</span><span class="n">DynamicInvoke</span><span class="p">(</span><span class="k">this</span><span class="p">,</span> <span class="k">new</span> <span class="n">EventArgs</span><span class="p">())</span> <span class="k">is</span> <span class="n">Task</span> <span class="n">task</span><span class="p">)</span>
                <span class="k">yield</span> <span class="k">return</span> <span class="n">task</span><span class="p">;</span>
    <span class="p">}</span>

    <span class="c1">/// &lt;summary&gt;</span>
    <span class="c1">/// Typical event invokation </span>
    <span class="c1">/// &lt;/summary&gt;</span>
    <span class="k">public</span> <span class="k">void</span> <span class="nf">TriggerEvent</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="n">MyEvent</span><span class="p">(</span><span class="k">this</span><span class="p">,</span> <span class="k">new</span> <span class="n">EventArgs</span><span class="p">());</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// Exceptions are caught here</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></div>


<p>In both cases, calling <code>TriggerEventAsync()</code> or  <code>TriggerEvent()</code> will handle exceptions thrown in either synchronous or asynchronous code blocks.</p>
<p>I have written some tests with Nunit3 and .Net Core 1.1 to illustrate working examples of exceptions being correctly handled up the stack. </p>
<p><a href="https://gist.github.com/NZSmartie/2b66924cffc98047f995c7f3813046eb">Handle Exceptions from async EventHandler with Nunit tests </a></p>
<p>Feedback is appreciated!</p>
  </div>

  </div>
</body>
</html>